image: markhobson/node-chrome

cache:
  key: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}
  paths:
    - node_modules/
  policy: pull-push

before_script:
  - apt-get update && apt-get update

stages:
  - install_dependencies
  - build
  - test
  - deploy

install_dependencies:
  stage: install_dependencies
  only:
    - master
  script:
    - npm install

build:
  stage: build
  only:
    - master
  script:
    - npm run build:prod
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - dist/

test:
  stage: test
  only:
    - master
  script:
    - npm run test-ci
